//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/remedy-controller/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	componentbaseconfig "k8s.io/component-base/config"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AzureConfiguration)(nil), (*config.AzureConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AzureConfiguration_To_config_AzureConfiguration(a.(*AzureConfiguration), b.(*config.AzureConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AzureConfiguration)(nil), (*AzureConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AzureConfiguration_To_v1alpha1_AzureConfiguration(a.(*config.AzureConfiguration), b.(*AzureConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureFailedVMRemedyConfiguration)(nil), (*config.AzureFailedVMRemedyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AzureFailedVMRemedyConfiguration_To_config_AzureFailedVMRemedyConfiguration(a.(*AzureFailedVMRemedyConfiguration), b.(*config.AzureFailedVMRemedyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AzureFailedVMRemedyConfiguration)(nil), (*AzureFailedVMRemedyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AzureFailedVMRemedyConfiguration_To_v1alpha1_AzureFailedVMRemedyConfiguration(a.(*config.AzureFailedVMRemedyConfiguration), b.(*AzureFailedVMRemedyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureOrphanedPublicIPRemedyConfiguration)(nil), (*config.AzureOrphanedPublicIPRemedyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration_To_config_AzureOrphanedPublicIPRemedyConfiguration(a.(*AzureOrphanedPublicIPRemedyConfiguration), b.(*config.AzureOrphanedPublicIPRemedyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AzureOrphanedPublicIPRemedyConfiguration)(nil), (*AzureOrphanedPublicIPRemedyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AzureOrphanedPublicIPRemedyConfiguration_To_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration(a.(*config.AzureOrphanedPublicIPRemedyConfiguration), b.(*AzureOrphanedPublicIPRemedyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AzureConfiguration_To_config_AzureConfiguration(in *AzureConfiguration, out *config.AzureConfiguration, s conversion.Scope) error {
	out.OrphanedPublicIPRemedy = (*config.AzureOrphanedPublicIPRemedyConfiguration)(unsafe.Pointer(in.OrphanedPublicIPRemedy))
	out.FailedVMRemedy = (*config.AzureFailedVMRemedyConfiguration)(unsafe.Pointer(in.FailedVMRemedy))
	return nil
}

// Convert_v1alpha1_AzureConfiguration_To_config_AzureConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AzureConfiguration_To_config_AzureConfiguration(in *AzureConfiguration, out *config.AzureConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AzureConfiguration_To_config_AzureConfiguration(in, out, s)
}

func autoConvert_config_AzureConfiguration_To_v1alpha1_AzureConfiguration(in *config.AzureConfiguration, out *AzureConfiguration, s conversion.Scope) error {
	out.OrphanedPublicIPRemedy = (*AzureOrphanedPublicIPRemedyConfiguration)(unsafe.Pointer(in.OrphanedPublicIPRemedy))
	out.FailedVMRemedy = (*AzureFailedVMRemedyConfiguration)(unsafe.Pointer(in.FailedVMRemedy))
	return nil
}

// Convert_config_AzureConfiguration_To_v1alpha1_AzureConfiguration is an autogenerated conversion function.
func Convert_config_AzureConfiguration_To_v1alpha1_AzureConfiguration(in *config.AzureConfiguration, out *AzureConfiguration, s conversion.Scope) error {
	return autoConvert_config_AzureConfiguration_To_v1alpha1_AzureConfiguration(in, out, s)
}

func autoConvert_v1alpha1_AzureFailedVMRemedyConfiguration_To_config_AzureFailedVMRemedyConfiguration(in *AzureFailedVMRemedyConfiguration, out *config.AzureFailedVMRemedyConfiguration, s conversion.Scope) error {
	out.RequeueInterval = in.RequeueInterval
	out.SyncPeriod = in.SyncPeriod
	out.NodeSyncPeriod = in.NodeSyncPeriod
	out.MaxGetAttempts = in.MaxGetAttempts
	out.MaxReapplyAttempts = in.MaxReapplyAttempts
	return nil
}

// Convert_v1alpha1_AzureFailedVMRemedyConfiguration_To_config_AzureFailedVMRemedyConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AzureFailedVMRemedyConfiguration_To_config_AzureFailedVMRemedyConfiguration(in *AzureFailedVMRemedyConfiguration, out *config.AzureFailedVMRemedyConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AzureFailedVMRemedyConfiguration_To_config_AzureFailedVMRemedyConfiguration(in, out, s)
}

func autoConvert_config_AzureFailedVMRemedyConfiguration_To_v1alpha1_AzureFailedVMRemedyConfiguration(in *config.AzureFailedVMRemedyConfiguration, out *AzureFailedVMRemedyConfiguration, s conversion.Scope) error {
	out.RequeueInterval = in.RequeueInterval
	out.SyncPeriod = in.SyncPeriod
	out.NodeSyncPeriod = in.NodeSyncPeriod
	out.MaxGetAttempts = in.MaxGetAttempts
	out.MaxReapplyAttempts = in.MaxReapplyAttempts
	return nil
}

// Convert_config_AzureFailedVMRemedyConfiguration_To_v1alpha1_AzureFailedVMRemedyConfiguration is an autogenerated conversion function.
func Convert_config_AzureFailedVMRemedyConfiguration_To_v1alpha1_AzureFailedVMRemedyConfiguration(in *config.AzureFailedVMRemedyConfiguration, out *AzureFailedVMRemedyConfiguration, s conversion.Scope) error {
	return autoConvert_config_AzureFailedVMRemedyConfiguration_To_v1alpha1_AzureFailedVMRemedyConfiguration(in, out, s)
}

func autoConvert_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration_To_config_AzureOrphanedPublicIPRemedyConfiguration(in *AzureOrphanedPublicIPRemedyConfiguration, out *config.AzureOrphanedPublicIPRemedyConfiguration, s conversion.Scope) error {
	out.RequeueInterval = in.RequeueInterval
	out.SyncPeriod = in.SyncPeriod
	out.ServiceSyncPeriod = in.ServiceSyncPeriod
	out.DeletionGracePeriod = in.DeletionGracePeriod
	out.MaxGetAttempts = in.MaxGetAttempts
	out.MaxCleanAttempts = in.MaxCleanAttempts
	return nil
}

// Convert_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration_To_config_AzureOrphanedPublicIPRemedyConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration_To_config_AzureOrphanedPublicIPRemedyConfiguration(in *AzureOrphanedPublicIPRemedyConfiguration, out *config.AzureOrphanedPublicIPRemedyConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration_To_config_AzureOrphanedPublicIPRemedyConfiguration(in, out, s)
}

func autoConvert_config_AzureOrphanedPublicIPRemedyConfiguration_To_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration(in *config.AzureOrphanedPublicIPRemedyConfiguration, out *AzureOrphanedPublicIPRemedyConfiguration, s conversion.Scope) error {
	out.RequeueInterval = in.RequeueInterval
	out.SyncPeriod = in.SyncPeriod
	out.ServiceSyncPeriod = in.ServiceSyncPeriod
	out.DeletionGracePeriod = in.DeletionGracePeriod
	out.MaxGetAttempts = in.MaxGetAttempts
	out.MaxCleanAttempts = in.MaxCleanAttempts
	return nil
}

// Convert_config_AzureOrphanedPublicIPRemedyConfiguration_To_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration is an autogenerated conversion function.
func Convert_config_AzureOrphanedPublicIPRemedyConfiguration_To_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration(in *config.AzureOrphanedPublicIPRemedyConfiguration, out *AzureOrphanedPublicIPRemedyConfiguration, s conversion.Scope) error {
	return autoConvert_config_AzureOrphanedPublicIPRemedyConfiguration_To_v1alpha1_AzureOrphanedPublicIPRemedyConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*componentbaseconfig.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.Azure = (*config.AzureConfiguration)(unsafe.Pointer(in.Azure))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*configv1alpha1.ClientConnectionConfiguration)(unsafe.Pointer(in.ClientConnection))
	out.Azure = (*AzureConfiguration)(unsafe.Pointer(in.Azure))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}
