#!/usr/bin/env bash
set -e

FLAVOR_TESTRUN_CHART=""
FLAVOR_CONFIG="min-shoot-flavor.yaml"
TM_LANDSCAPE="external"
LANDSCAPE=""
ARGUMENTS=""

repo_dir="$(readlink -f "$(dirname "${0}")/..")"


for i in "$@"
do
echo $i
case $i in
        -flavor-tm-chart=*|--flavor-tm-chart=*)
        FLAVOR_TESTRUN_CHART="${i#*=}"
        shift
    ;;
        -flavor-config=*|--flavor-config=*)
        FLAVOR_CONFIG="${i#*=}"
        shift
    ;;
        -tm-landscape=*|--tm-landscape=*)
        TM_LANDSCAPE="${i#*=}"
        shift
    ;;
        -landscape=*|--landscape=*)
        LANDSCAPE="${i#*=}"
        shift
    ;;
        --)
        ARGUMENTS="${@:2}"
        break
    ;;
    *)
        # unknown option
        echo "Unkown option ${i#*=}"
        exit 1
    ;;
esac
done

if [[ $TM_LANDSCAPE == "" ]]; then
    echo "Required parameter: -tm-landscape : external | internal"
    exit 1
fi
if [[ $LANDSCAPE == "" ]]; then
    echo "Required parameter: -landscape"
    exit 1
fi

if [[ $TM_LANDSCAPE == "external" ]]; then
    TM_CONFIG_NAME=testmachinery
    S3_ENDPOINT="storage.googleapis.com"
fi

echo "Testmachinery config name: ${TM_CONFIG_NAME}"
echo "Testmachinery landscape: ${TM_LANDSCAPE}"
echo "Arguments: ${ARGUMENTS}"


export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
mkdir -p /tm
TM_CLUSTER=/tm/kubeconfig
ACTIVE_GARDEN_CLUSTER=/tm/gardener.kubeconfig
cli.py config attribute --cfg-type kubernetes --cfg-name garden-dev-virtual --key kubeconfig > $ACTIVE_GARDEN_CLUSTER

if [[ $FLAVOR_TESTRUN_CHART != "" ]]; then
    FLAVOR_TESTRUN_CHART_PATH="$SOURCE_PATH/.ci/testruns/$FLAVOR_TESTRUN_CHART"
fi

mkdir -p /tm
cli.py config attribute --cfg-type kubernetes --cfg-name $TM_CONFIG_NAME --key kubeconfig > $TM_CLUSTER

export KUBECONFIG=$TM_CLUSTER

test_version="$(cat ${repo_dir}/VERSION)"

# timeout to 6h
/testrunner run \
    --gardener-kubeconfig-path=$ACTIVE_GARDEN_CLUSTER \
    --tm-kubeconfig-path=$TM_CLUSTER \
    --timeout=21600 \
    --interval=60 \
    --es-config-name=sap_internal \
    --landscape=$LANDSCAPE \
    --s3-endpoint=$S3_ENDPOINT \
    --s3-ssl=true \
    --shoot-name="tm-" \
    --flavored-testruns-chart-path=$FLAVOR_TESTRUN_CHART_PATH \
    --flavor-config=$SOURCE_PATH/.ci/flavours/$FLAVOR_CONFIG \
    --set "testVersion=${test_version}" \
    $ARGUMENTS