#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

apt-get update
apt-get install -y unzip python3 python3-venv

git config --global user.email "kubernetes.concourse@gmail.com"
git config --global user.name "kubernetes-concourse"

mkdir -p /go/src/github.wdf.sap.corp/kubernetes/remedy-controller
cp -r . /go/src/github.wdf.sap.corp/kubernetes/remedy-controller
cd /go/src/github.wdf.sap.corp/kubernetes/remedy-controller

make verify-extended
