#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

git config --global user.email "kubernetes.concourse@gmail.com"
git config --global user.name "kubernetes-concourse"

make verify-extended
