apiVersion: apps/v1
kind: Deployment
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
  labels:
    app: remedy-controller-azure
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: remedy-controller-azure
  template:
    metadata:
      annotations:
        checksum/configmap-remedy-controller-azure-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/configmap-cloud-provider-config: {{ include (print $.Template.BasePath "/configmap-cloud-provider-config.yaml") . | sha256sum }}
      labels:
        app: remedy-controller-azure
    spec:
      serviceAccountName: remedy-controller-azure
      containers:
      - name: remedy-controller-azure
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /remedy-controller-azure
        - --namespace={{ .Release.Namespace }}
        - --config-file=/etc/remedy-controller-azure/config/config.yaml
        - --infrastructure-config=/etc/kubernetes/cloudprovider/cloudprovider.conf
        - --leader-election=true
        - --publicipaddress-max-concurrent-reconciles={{ .Values.controllers.publicipaddress.concurrentSyncs }}
        - --virtualmachine-max-concurrent-reconciles={{ .Values.controllers.virtualmachine.concurrentSyncs }}
        - --service-max-concurrent-reconciles={{ .Values.controllers.service.concurrentSyncs }}
        - --node-max-concurrent-reconciles={{ .Values.controllers.node.concurrentSyncs }}
        - --metrics-bind-address=:{{.Values.manager.metricsPort}}
        - --target-metrics-bind-address=:{{.Values.targetManager.metricsPort}}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --target-disable-controllers={{ .Values.targetDisableControllers | join "," }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: {{ .Values.manager.metricsPort }}
          protocol: TCP
        - name: target-metrics
          containerPort: {{ .Values.targetManager.metricsPort }}
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/remedy-controller-azure/config
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider
      volumes:
      - name: config
        configMap:
          name: remedy-controller-azure-config
      - name: cloud-provider-config
        configMap:
          name: cloud-provider-config
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
{{- end }}
