// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/remedy-controller/pkg/utils (interfaces: ExpiringCache)
//
// Generated by this command:
//
//	mockgen -package utils -destination=mocks.go github.com/gardener/remedy-controller/pkg/utils ExpiringCache
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockExpiringCache is a mock of ExpiringCache interface.
type MockExpiringCache struct {
	ctrl     *gomock.Controller
	recorder *MockExpiringCacheMockRecorder
	isgomock struct{}
}

// MockExpiringCacheMockRecorder is the mock recorder for MockExpiringCache.
type MockExpiringCacheMockRecorder struct {
	mock *MockExpiringCache
}

// NewMockExpiringCache creates a new mock instance.
func NewMockExpiringCache(ctrl *gomock.Controller) *MockExpiringCache {
	mock := &MockExpiringCache{ctrl: ctrl}
	mock.recorder = &MockExpiringCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpiringCache) EXPECT() *MockExpiringCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExpiringCache) Delete(key any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", key)
}

// Delete indicates an expected call of Delete.
func (mr *MockExpiringCacheMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExpiringCache)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockExpiringCache) Get(key any) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExpiringCacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExpiringCache)(nil).Get), key)
}

// Set mocks base method.
func (m *MockExpiringCache) Set(key, value any, ttl time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value, ttl)
}

// Set indicates an expected call of Set.
func (mr *MockExpiringCacheMockRecorder) Set(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockExpiringCache)(nil).Set), key, value, ttl)
}
