name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path:
    permissions:
      contents: read

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: remedy-controller-image
            target:
            oci-repository: gardener/remedy-controller/remedy-controller-azure
    with:
      name: ${{ matrix.args.name }}
      version: ${{ needs.prepare.outputs.version }}
      target: ${{ matrix.args.target }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: ${{ matrix.args.oci-repository }}
      oci-platforms: linux/amd64,linux/arm64
      extra-tags:

  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - name: run-test
        shell: bash
        run: |
          set -eu
          mkdir /tmp/blobs.d
          .ci/verify |& tee /tmp/blobs.d/verify-log.txt
          # verify calls `make sast-report`, which generates `gosec-report.sarif`
          tar czf /tmp/blobs.d/verify-log.tar.gz -C /tmp/blobs.d verify-log.txt
          tar czf /tmp/blobs.d/gosec-report.tar.gz gosec-report.sarif
      - name: add-reports-to-component-descriptor
        uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            - name: gosec-report
              relation: local
              access:
                type: localBlob
                localReference: gosec-report.tar.gz
              labels:
                - name: gardener.cloud/purposes
                  value:
                    - lint
                    - sast
                    - gosec
                - name: gardener.cloud/comment
                  value: |
                    we use gosec (linter) for SAST scans
                    see: https://github.com/securego/gosec
            - name: test-results
              relation: local
              access:
                type: localBlob
                localReference: verify-log.tar.gz
              labels:
                - name: gardener.cloud/purposes
                  value:
                    - test
